--- 
author: Chris Prather <perigrin@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.650
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Bundle::Bender
name: Bundle-Bender
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
  version: 0
version: 1.0
